 # Numpy Task


In [1]:
import numpy as np

# 1	Create a 1D NumPy array of numbers from 0 to 9.	


In [2]:
arr = np.arange(10)

print(arr)


[0 1 2 3 4 5 6 7 8 9]


# 2	Create a 2D array of shape (3, 3) with all elements as 1.	


In [3]:
array_2d = np.ones((3, 3), dtype=int)
array_2d


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# 3	Generate a NumPy array of 15 random integers between 10 and 50.	


In [4]:
random_array = np.random.randint(10, 50, size=15)
random_array

array([29, 23, 31, 30, 12, 35, 34, 49, 34, 14, 36, 37, 37, 39, 37],
      dtype=int32)

# 4	Create an array of 5 evenly spaced numbers between 0 and 1 (inclusive).	


In [5]:
evenly_spaced = np.linspace(0, 1, 5)
evenly_spaced

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# 5	Create a 4x4 identity matrix using NumPy.	

In [6]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 7	Create a 3x3 array with values from 1 to 9, then extract the second column.	


In [7]:
array_3x3 = np.arange(1, 10).reshape(3, 3)
second_column = array_3x3[:, 1]
print("3x3 Array:\n", array_3x3)
print("\nSecond Column:\n", second_column)


3x3 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Second Column:
 [2 5 8]


# 8	Create a 1D array with 10 elements and reshape it into a 2x5 matrix.	


In [8]:
array_1d = np.arange(10)
matrix_2x5 = array_1d.reshape(2, 5)
print("1D Array:", array_1d)
print("\nReshaped 2x5 Matrix:\n", matrix_2x5)

1D Array: [0 1 2 3 4 5 6 7 8 9]

Reshaped 2x5 Matrix:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


# 9	Create two 2x2 matrices and perform matrix multiplication.	


In [9]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
A,B*2


(array([[1, 2],
        [3, 4]]),
 array([[10, 12],
        [14, 16]]))

# 10 create 2x2 matrix and multiply by two different numbers

In [10]:
A = np.array([[4, 2],
              [3, 4]])

B = np.array([[5, 4],
              [7, 6]])
A*2,B*3

(array([[8, 4],
        [6, 8]]),
 array([[15, 12],
        [21, 18]]))

# 11	Given the array arr = np.array([5, 12, 7, 18, 3]), replace all values greater than 10 with 100.	


In [11]:
arr = np.array([5, 12, 7, 18, 3])
arr[arr > 10] = 100
arr

array([  5, 100,   7, 100,   3])